# Generated by Django 5.0.2 on 2024-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='business',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
