# Generated by Django 5.0.2 on 2024-03-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_delete_wishlist'),
        ('users', '0005_alter_userprofile_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='ecommerce_app.product'),
        ),
    ]
