# Generated by Django 5.0.2 on 2024-03-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_delete_cart'),
        ('users', '0006_alter_userprofile_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='ecommerce_app.product'),
        ),
    ]
