# Generated by Django 5.0.2 on 2024-03-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_delete_cart'),
        ('users', '0007_userprofile_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='ecommerce_app.product'),
        ),
    ]
