# Generated by Django 5.0.2 on 2024-03-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
