# Generated by Django 5.0.2 on 2024-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids')], default='women', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
