# Generated by Django 5.0.2 on 2024-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_product_gender_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('tshirts', 'T-Shirts'), ('pants', 'Pants'), ('accessories', 'Accessories')], default='tshirts', max_length=200),
        ),
    ]
