# Generated by Django 5.0.2 on 2024-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortened_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
